module.exports = [
  "a fat",
  "a crazy",
  "a strong",
  "a little",
  "a skinny",
  "a ginormous",
  "a ridiculous",
  "a funny-looking",
  "an awesome",
  "a sly",
  "an old",
  "a kindly",
  "a bright",
  "a young",
  "a cute",
  "a sinister",
  "a french",
  "a hairy",
  "a sneaky",
  "a keepsake",
  "a GIANT",
  "a pocket",
  "a really tough",
  "a twinkling",
  "a wrinkly",
  "a mentally disabled",
  "a striped",
  "a famous",
  "a dead",
  "an hairless",
  "a sadistic",
  "a metal",
  "a wild",
  "a domesticated",
  "an abnormal",
  "a medicated",
  "a cocky",
  "a massive",
  "a disrespectful",
  "an impressive",
  "an out of control",
  "an internet worthy",
  "an hilarious",
  "a sexy",
  "an hot",
  "a very tactful",
  "a bearded",
  "a duck-like",
  "a violent",
  "a slimy",
  "an insanely creepy",
  "an embarrassed to the bone",
  "a self-centered",
  "a talking",
  "a naked",
  "an angry",
  "a shaky",
  "a deep",
  "a sick",
  "a zippy",
  "a sticky",
  "a fluffy",
  "a frozen",
  "an unholy",
  "a painfully honest",
  "a filthy",
  "a fighting",
  "a bonkers",
  "an harsh",
  "a frisky",
  "a greedy",
  "a crawly",
  "an insane",
  "an hideous",
  "an ungodly",
  "an abusive",
  "a drunken",
  "an hateful",
  "an idiotic",
  "a twisted",
  "an useless",
  "a yapping",
  "a magical",
  "an indecent",
  "a godawful",
  "an arrogant",
  "a confused",
  "a flirting",
  "an high-end",
  "an insecure",
  "a maniacal",
  "a sickened",
  "a slippery",
  "a stubborn",
  "a tripping",
  "a vengeful",
  "a sinister",
  "a costumed",
  "a cowardly",
  "an haunting",
  "a startled",
  "an alcoholic",
  "a demanding",
  "a shivering",
  "an offensive",
  "a nighttime",
  "a startling",
  "a disgusting",
  "a slap happy",
  "a disturbing",
  "an adulterous",
  "a blathering",
  "a flickering",
  "a rebellious",
  "an impertinent",
  "a bull headed",
  "a hyperactive",
  "an infuriating",
  "an outnumbered",
  "a pea-brained",
  "a territorial",
  "an underhanded",
  "a zombie like",
  "a mischievous",
  "an at-the-ready",
  "a free-loading",
  "an house-broken",
  "an up-to-no-good",
  "a cruel-hearted",
  "a misunderstood",
  "a narrow-minded",
  "a self-absorbed",
  "a bat-shit-crazy",
  "a fiercely-loyal",
  "an out-of-control",
  "a fear-inspiring",
  "a bat shit crazy",
  "a mentally impaired",
];
