module.exports = [
  ", right?",
  ", like I said.",
  ", just like yo' momma!",
  " again!",
  "- without flinching!",
  " as if it $was normal.",
  "... kinda.",
  " but later regretted it.",
  " and wouldn't stop dancing.",
  " then died.",
  " for you.",
  " for $subject.",
  ", resulting in the early demise of $subject.",
  " and didn't even realise it.",
  ". Then $person copied $them.",
  "... but nobody will believe me.",
];
