module.exports = [
  "$a-adj dingle berry",
  "$a-adj dragon",
  "$a-adj electric furnace",
  "$a-adj flask",
  "$a-adj goblin",
  "$a-adj guy",
  "$a-adj hyena",
  "$a-adj kitty",
  "$a-adj landscape painting",
  "$a-adj man",
  "$a-adj monkey",
  "$a-adj multi-billionaire",
  "$a-adj patrolman",
  "$a-adj penguin",
  "$a-adj pervert",
  "$a-adj police squad",
  "$a-adj private investor",
  "$a-adj psychic",
  "$a-adj sandwich",
  "$a-adj tank",
  "$a-adj travel guidebook",
  "$a-adj weed whacker",
  "$a-adj woman",
  "$a-adj wrinkle",
  "$adj criminal",
  "$adj legs",
  "$adj machete",
  "$an-adj irish cottage",
  "$an-adj octopus",
  "$person's mum",
  "$the-adj candlestick maker",
  "$the-adj president of the night",
  "$their background story",
  "$their brethren",
  "$their dad",
  "$their dog",
  "$their face",
  "$their gaming laptop",
  "$their goal in life",
  "$their lightsabre",
  "$their marketing idea",
  "$their mood",
  "$their personal credit line",
  "$their place of business",
  "$their tongue",
  "$their useless brakes",
  "$themself",
  "a coffee pot",
  "a french chef",
  "a knife",
  "a legal warrant",
  "a napkin",
  "a pen",
  "a pistol",
  "a rough-skinned newt",
  "a skullcap",
  "a toaster",
  "an air guitar",
  "$an-adj idiot",
  "some antidepressant drugs",
  "some corn cake",
  "some deer antlers",
  "some dog poop",
  "some fat",
  "some laser beams",
  "some lettuce",
  "some liquid oxygen",
  "some nibblets",
  "some people who are hurt",
  "some poop",
  "some sweet tailpipe",
  "some water",
  "the factory reset button",
  "the idea $they suggested",
  "the love of $their life",
  "the national security agency",
  "the new version",
  "the sound barrier",
  "the toilet seat",
  "Cthulu",
  "mad cow disease",
  "nothing",
  "you",
];
