module.exports = [
  "at the big game",
  "down the stairs",
  "in a coffin",
  "over the moon",
  "for $subject",
  "in place",
  "instead of $person",
  "in the bathroom",
  "followed by $object",
  "on top of $subject",
  "with $subject on top",
  "with $subject",
  "right behind $subject",
  "in front of $subject",
  "in the highest tower",
  "in $their parents' room",
  "without knowing",
  "between the sofa cushions",
  "in $person's dreams",
  "around the world",
  "nowhere",
  "all alone",
  "in the basement",
  "while in therapy",
  "down at the hunting grounds",
  "with the international law enforcement agency",
  "at the speed of light",
  "during the reading party",
  "through a mess",
  "in a volcanic crater",
  "while $they threw a hissy fit",
  "while $they meditated",
  "in the haunted graveyard",
  "in a state of uncleanliness",
];
